
version: 2

sources:
    - name: stage
      #For bigquery:
      database: zoomcampproject
      schema: f1_data_all

      tables:
        - name: external_table_constructor_results
        - name: external_table_races
        - name: external_table_constructors
        - name: f1_stage